# Generated by Django 3.2.8 on 2021-10-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre')),
                ('imagen', models.ImageField(max_length=480, upload_to='articulos', verbose_name='Imagen', width_field=640)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Precio')),
                ('cantidd', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Cantidad')),
            ],
            options={
                'verbose_name': 'Articulo',
                'verbose_name_plural': 'Articulos',
            },
        ),
    ]
