# Generated by Django 3.2.8 on 2021-10-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_auto_20211016_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=18, verbose_name='Cantidad'),
            preserve_default=False,
        ),
    ]
