# Generated by Django 3.2.8 on 2021-10-17 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pedido', '0003_articulo_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('facturado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Cantidad')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Precio')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Subt')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedido.articulo')),
            ],
            options={
                'verbose_name': 'DetallePedido',
                'verbose_name_plural': 'DetallePedidos',
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Cantidad')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Precio')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Subt')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedido.articulo')),
            ],
            options={
                'verbose_name': 'DetalleCompra',
                'verbose_name_plural': 'DetalleCompras',
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
            },
        ),
    ]
