# Generated by Django 3.2.8 on 2021-10-17 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0005_auto_20211016_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallecompra',
            name='articulo',
        ),
        migrations.RemoveField(
            model_name='detallecompra',
            name='compra',
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='articulo',
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Compra',
        ),
        migrations.DeleteModel(
            name='DetalleCompra',
        ),
        migrations.DeleteModel(
            name='DetallePedido',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
